# Icons for l command (nerd font icons)
default = ""
symlink = ""
symlink_dir = ""
symlink_exec = ""
symlink_file = ""
directory = ""
current_dir = ""
locked_dir = "󰉐"
executable = ""
file = ""
binary = ""
device = ""
socket = "󰒍"
fifo = "󰟥"
git_modified = ""
git_untracked = "󰛑"
git_staged = ""
git_deleted = ""
git_upstream = ""
readonly = ""
count_files = ""
count_lines = "󰍜"
count_pixels = "󰹑"
cursor = "❯"
[extensions]
jpg,png,fig,webp,bpm,ico = ""
mp3,wav,flac,ogg,m4a = "󰝚"
mp4,mkv,avi,mov,webm = "󰿎"
