# Icons for l command (nerd font icons)
default = ""
symlink = ""
symlink_dir = ""
symlink_exec = ""
symlink_file = ""
closed_directory = ""
open_directory = ""
locked_dir = "󰉐"
executable = ""
file = ""
binary = ""
device = ""
socket = "󰒍"
fifo = "󰟥"
git_modified = ""
git_untracked = "󰛑"
git_staged = ""
git_deleted = ""
git_upstream = ""
readonly = ""
count_files = ""
count_lines = "󰍜"
count_pages = ""
count_pixels = "󰹑"
count_duration = ""
cursor = "❯"
[extensions]
jpg,png,gif,webp,bmp,ico = ""
mp3,wav,flac,ogg,m4a,m4b = "󰝚"
mp4,mkv,avi,mov,webm = "󰿎"
